apiVersion: v1
kind: Service
metadata:
  name: google-cloud-sample
  labels:
    app: google-cloud-sample
    tier: service
spec:
  type: NodePort
  ports:
  - port: 8080
  #selector should match pod labels
  selector:
    app: google-cloud-sample